inherit_from: .rubocop_todo.yml

inherit_gem:
  rubocop-rock: defaults.yml

inherit_mode:
  merge:
  - AllowedNames

AllCops:
  TargetRubyVersion: "2.5"

Naming/MethodParameterName:
  AllowedNames:
  - ws

Metrics/BlockLength:
  Exclude:
    - 'test/**/test_*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'test/**/test_*.rb'